name: Deploy to Netlify
run-name: "Deploy to Netlify-  ${{ github.ref_name }}"

on:
  workflow_run:
    workflows: ["Preprocess Data & Build"]
    types:
      - completed
    conclusion: success


jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy Netlify from ${{ github.event.workflow_run.head_branch }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download preprocessed files
        uses: actions/download-artifact@v4
        with:
          name: site-files
          path: www/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: ./www
          production-branch: main
          alias: deploy-preview
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}


  on-failure:
    name: Preprocessing and Build Failed
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "Data was not able to be processed or built was failure. Deployment cancelled."