
name: Preprocess Data & Build

on:
  push:
    branches:
      - main
      - deploy-preview  # add other branches as needed
    

jobs:
  preprocess-and-build:
    #concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          
      - name: Python
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.8'

      - name: Install and Build üîß
        run: |
          pip install --upgrade pip==24.0
          cd DataBuilder/
          pip install -r requirements.txt
          python src/main.py -f ../Data/inputfile.csv -o ../Data/order.csv -tt -c --auto-place
          cd ../VerbApp
          npm install --force
          npm install -g ionic --force
          ionic build --prod -- --deploy-url /BQWordWeaverLite/ --base-href /BQWordWeaverLite/ --output-path=../www

      - name: Upload generated files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: site-files
          path: www/
